# Generated by Django 5.2.1 on 2025-05-21 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion',
            name='periodo',
            field=models.CharField(choices=[('PRIMERO', 'Primero'), ('SEGUNDO', 'Segundo'), ('TERCERO', 'Tercero'), ('FINAL', 'Final')], default='Primero', max_length=8),
            preserve_default=False,
        ),
    ]
